### ISSUE TITLE
No license declaration in repository

### ISSUE THREAD

**Issue by ngoldbaum** [N-BodyShop/changa#11]
I see on http://faculty.washington.edu/trq/hpcc/tools/changa.html that the intention is to release ChaNGa under the GPL. As far as I can see there is no declaration of this in the source code itself. It would make things clearer to include a copy of the intended license (either GPLv2 or GPLv3) in the source code and release tarballs.

**Comment by trquinn** [comment]
An oversight.  Currently commit a90fe7b6b7a68f4fa046a7862cd3ebdab49b909e in the PPL repository

**Comment by ngoldbaum** [comment]
Thanks! Found the PPL gerrit instance and I see the license has been added: https://charm.cs.illinois.edu/gerrit/#/q/project:cosmo/changa

Closing.
