### ISSUE TITLE
Ewald Splitting parameter alpha is hard-coded in Ewald.C

### ISSUE THREAD

**Issue by hkayabilisim** [N-BodyShop/changa#12]
Hi,

I noticed that Ewald's splitting parameter alpha is hard-coded in Ewald.C file as alpha=2/L. Is there a specific reason for not to include as an adjustable input parameter such as dEwCut or dEwhCut?

Thank you

**Comment by trquinn** [comment]
The value for alpha has been inherited from previous works without any testing.  See Hernquist, Bouchet & Suto 1991, who reference Sangster & Dixon, 1976.

One non-obvious worry about changing alpha: the Ewald expansion has round-off errors at the origin which are mitigated by doing a Taylor expansion.  The switch-over radius (also hard coded, but determined empirically) will depend on alpha.

**Comment by hkayabilisim** [comment]
Thank you for the information. I checked Hernquist, Bouchet & Suto 1991 and especially the Equation 2.8 in the related article.

(1) I noticed that there is a pre-calculated constant (U \approx 2.8372975) in the formula. But in the Ewald.C of ChaNGa, I couldn't find it. Is it because you follow another recipe other than Hernquist's?

(2) By using the test configuration in testcosmo/cube300, I adjusted the Ewald's real and reciprocal space cutoffs (dEwCut and dEwhCut) to check how important they are on the calculated potential energy at the beginning of the time integration.  When I look at the data I see that even if I set them to zero, the potential doesn't change significantly.  I was expecting a more dramatic change.

|alpha |dEwCut |dEwhCut  |Potential
|----- |------ |-------  |---------
|2/L   |0      |0        |0.00118147 
|2/L   |0.0625 |0.0625   |0.00118147
|2/L   |0.0625 |2.8      |0.00118157
|2/L   |0.125  |2.8      |0.00118157
|2/L   |0.25   |2.8      |0.00118157
|2/L   |0.5    |2.8      |0.00118157
|2/L   |1      |2.8      |0.00118157
|2/L   |2      |2.8      |0.0011816
|2/L   |2.6    |2.8      |0.0011816 (default parameters)
|2/L   |4      |2.8      |0.0011816
|2/L   |8      |2.8      |0.0011816 
|2/L   |2.6    |1        |0.0011816
|2/L   |2.6    |2        |0.0011816
|2/L   |2.6    |4        |0.0011816 
|2/L   |2.6    |8        |0.0011816 

(3) I implemented Hernquist's Ewald formula, and want to test on testcosmo/cube300 data and compare with the potential energy calculated with ChaNGa. But it is not easy because of specific details in ChaNGa such as gravitational softening, comoving coordinates, and other constants that I probably don't know yet. I'll be glad if you show me how to set the parameters of ChaNGa so that I could compare its potential energy with the one calculated with the straightforward implementation of Hernquist, Bouchet & Suto 1991.

**Comment by trquinn** [comment]
The "U" constant is just a gauge choice, so it can be ignored.

Look at https://github.com/N-BodyShop/direct for a code that uses the Ewald formula in a straightforward manner to compare with ChaNGa.  This is the code we used to check the (force) accuracy of ChaNGa.

**Comment by hkayabilisim** [comment]
Thank you! This is very helpfull because I was looking for a way to verify
yet another periodic n-body code that I'm working on.
