### ISSUE TITLE
can not find xdr when compiling

### ISSUE THREAD

**Issue by wuchenglon** [N-BodyShop/changa#134]
It  returned me as follow when I compiling an old version of ChaNga:
XDR missing, attempting to use xdr with package
Try downloading the xdr package and place it in the parent directory.
And do a make in ../xdr

I don't what is XDR, and I can't find it any place.

**Comment by trquinn** [comment]
On more recent OSs, this has moved from the standard C library to "libtirpc".  Try to install the libtirpc development library for your operating system (on Fedora, it is the "libtirpc-devel" package.)

**Comment by wuchenglon** [comment]
> 在最近的操作系统上，这已经从标准的C库转移到了“libtirpc”。尝试为您的操作系统安装 libtirpc 开发库（在 Fedora 上，它是“libtirpc-devel”软件包）。

I find it's already installed libtirpc-common(1.3.2-2ubuntu0.1) and libtirpc-dev(1.3.2-2ubuntu0.1) , so did I reinstall an old version package ?

**Comment by trquinn** [comment]
Could you try a more recent version of ChaNGa?  (version 3.4 or later).

**Comment by trquinn** [comment]
Release 3.4 was cut in Sept, 2019.  What is in older versions that isn't in the latest release?

**Comment by wuchenglon** [comment]
> Release 3.4 was cut in Sept, 2019. What is in older versions that isn't in the latest release?

I generate an IC from diskpy , but it works a little weird in ChaNGa , diskpy's creator told me to use an old version and try again

**Comment by trquinn** [comment]
I think the best way forward is to debug the current versions of diskpy or ChaNGa.  Open up a new issue that fully describes the problem, and we can go from there.  I'm closing this for now.
