### ISSUE TITLE
New Build system does not pass -DGPU_LOCAL_TREE_WALK to charm compiler

### ISSUE THREAD

**Issue by hainest** [N-BodyShop/changa#27]
'configure --foo -> make -> configure --bar -> make' might break when not cleaning in between. Check that [Makefile](https://github.com/N-BodyShop/changa/blob/master/Makefile.in#L215) and [settings](https://github.com/N-BodyShop/changa/blob/master/Makefile.in#L235) deps are correct.

**Comment by trquinn** [comment]
I just found my problem: the "-DGPU_LOCAL_TREE_WALK" flag is only passed to nvcc, not to the charm compiles. Hence a bad CudaRequest structure on the C++ side.

**Comment by trquinn** [comment]
Fix is merged.
