### ISSUE TITLE
Update Developer's Guide

### ISSUE THREAD

**Issue by emapple** [N-BodyShop/changa#38]
The compile flags section of the developer's guide, [https://github.com/N-BodyShop/changa/wiki/Developer's-Guide#add-compile-flags](url), needs to be updated in light of 123c0d5db2736fafb88b0e3648987a4939073ebc.

**Comment by trquinn** [comment]
I did an @emapple, please proof read it.  Editing configure.ac and Makefile.in are a lot simpler now.

**Comment by emapple** [comment]
It looks good to me.
