### ISSUE TITLE
memcopy segfault when using Gnu on Cray

### ISSUE THREAD

**Issue by mand35** [N-BodyShop/changa#4]
I build ChaNGa on a Cray XC40 using the GNU compiling environment using the script below. 
The compilation of charm++ and changa went fine, but when I start the examples, teststep and testcosmo the application crashes with a segfault. A backtrace of the segfault lead me to a memcopy in CkReductionMsg::buildNew (see ATP backtrace below).

When I compile with Intel compiler the application runs fine. 
Is that a known issue?
============================
$> cat install.sh
#!/bin/bash
inst_dir=$PWD
module switch PrgEnv-cray/5.2.82 PrgEnv-gnu
cd charm
#./build charm++ gni-crayxc --with-production -j8
build ChaNGa gni-crayxc hugepages -j4 --with-production
cd ..
export CHARM_DIR=$inst_dir/charm/
cd changa/
./configure --prefix=$inst_dir/changa_inst CXX=CC CC=cc
make
cd ..
=======================================
$> cat run.pbs
#!/bin/bash
#PBS -N TEST
#PBS -l nodes=4:ppn=24
#PBS -l walltime=00:05:00     
cd $PBS_O_WORKDIR
CHANGA=../ChaNGa
aprun -n 4 -N 1 $CHANGA +ppn 6 cube300.param > test.out
=======================================
$> cat TEST.e851345
ATP Stack walkback for Rank 0 starting:
  _start@start.S:113
  __libc_start_main@libc-start.c:242
  main@0x20001626
  ConverseInit@0x2024e9d6
  ConverseRunPE@0x2024e809
  CsdScheduler@0x2025018c
  CsdScheduleForever@0x2024fe07
  _processHandler(void*, CkCoreState*)@0x2019ce2d
  CkDeliverMessageFree@0x20196f62
  CkArray::recvBroadcast(CkMessage*)@0x201bed67
  CkArrayBroadcaster::deliver(CkArrayMessage*, ArrayElement*, bool)@0x201be898
  CkLocRec_local::invokeEntry(CkMigratable*, void*, int, bool)@0x201b26fc
  CkDeliverMessageReadonly@0x20197255
  CkIndex_TreePiece::_call_drift_marshall51(void*, void*)@0x200523a9
  TreePiece::drift(double, int, int, double, double, int, bool, CkCallback const&)@0x20016747
  ArrayElement::contribute(int, void const*, CkReduction::reducerType, CkCallback const&, unsigned short)@0x201bbd9a
  CkReductionMsg::buildNew(int, void const*, CkReduction::reducerType, CkReductionMsg*)@0x201c7b40
  memcpy@memcpy.S:196

**Comment by trquinn** [comment]
Someone else has reported a similar problem, but I was not able to reproduce it.  What machine are you running on, and what version of charm, changa and utilities (git hashes) are you using?

**Comment by trquinn** [comment]
If I run through the script as you have posted, I get an error message: "aborting job:
+ppn cannot be used in non SMP version!".  This makes sense: your charm build did not specify "smp", but you used +ppn in the aprun command.  So here is my wild guess: you are picking up some other installation of charm on the system which is incompatible (possibly because another compiler was used) with what is in your source directory.

**Comment by mand35** [comment]
I am very sorry, There was a copy and paste issue. You are right the installation configuration and the runtime arguments were not consistent. I tried both versions with and without SMP during installation and the related options during runtime. 

The version I used are: 
charm $> git show
commit 5bf8ddf6805bddf423c421a226bb19a60ee7e493
Author: Sam White <white67@illinois.edu>
Date:   Wed Sep 14 15:56:52 2016 -0500

changa $ git show  commit 243ec6a0c5fdb0496b4b8bee198c81b5c8bfbd3d
Author: Thomas Quinn <trq@astro.washington.edu>
Date:   Sat Jan 30 12:15:20 2016 -0600

The machine is HLRS Cray XC40 called HazelHen.

**Comment by trquinn** [comment]
That version of ChaNGa is before the last release.  Have you tried anything more recent?  Also, what version of "utility" are you using: the crash you are getting is possibly caused by code in utility/structures.

**Comment by mand35** [comment]
I now also tested the latest versions, resulting in the same issue:

changa $> git log | head
commit 4b039741a2d468cf5ca20fe800afad9e857101e4
Author: Tom Quinn <trq@astro.washington.edu>
Date:   Sat Jun 18 16:45:28 2016 -0700

charm $> git log | head
commit 5bf8ddf6805bddf423c421a226bb19a60ee7e493
Author: Sam White <white67@illinois.edu>
Date:   Wed Sep 14 15:56:52 2016 -0500

utility $> git log | head
commit a2213e093407e217b108bb1105690758178e2e86
Merge: 2feaccf f1cc6e7
Author: Thomas Quinn <trq@astro.washington.edu>
Date:   Tue Jul 26 17:17:39 2016 -0500

**Comment by trquinn** [comment]
I used all these versions on the Piz Dora XC40 at CSCS, and it ran fine.  Perhaps we should look at compiler versions.  What is the output of  "module list"?

**Comment by mand35** [comment]
testcosmo $ module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.5
  2) eswrap/1.1.0-1.020200.1130.0
  3) switch/1.0-1.0502.60522.1.61.ari
  4) gcc/6.1.0
  5) craype-network-aries
  6) craype-hugepages16M
  7) craype-haswell
  8) craype/2.5.7
  9) cray-mpich/7.4.3
 10) torque/4.2.10
 11) moab/7.2.9-2014091214-96b8ec34-b9-SUSE11
 12) system/ws_tools
 13) system/hlrs-defaults
 14) cray-libsci/16.09.1
 15) udreg/2.3.2-1.0502.10518.2.17.ari
 16) ugni/6.0-1.0502.10863.8.29.ari
 17) pmi/5.0.10-1.0000.11050.0.0.ari
 18) dmapp/7.0.1-1.0502.11080.8.76.ari
 19) gni-headers/4.0-1.0502.10859.7.8.ari
 20) xpmem/0.1-2.0502.64982.5.3.ari
 21) dvs/2.5_0.9.0-1.0502.2188.1.116.ari
 22) alps/5.2.4-2.0502.9774.31.11.ari
 23) rca/1.0.0-2.0502.60530.1.62.ari
 24) atp/2.0.2
 25) PrgEnv-gnu/5.2.82

This was a good hint. When I switch back to gcc/5.3.0 it compiles and run fine. Seems that there is an issue with the gcc/6.1.0.
Would you investigate in this an report the compiler but if necessary?

**Comment by trquinn** [comment]
The charm developers are aware of a problem with gcc 6.1.0.  See the discussion here:
https://charm.cs.illinois.edu/redmine/issues/1045
I will investigate whether their workaround solves the problem in this case.

**Comment by trquinn** [comment]
I tested ChaNGa with gcc 6.2.1 on my laptop.  It dies with a similar error.  Recompiling Charm with the -fno-lifetime-dse flag as suggested in the redmine report appears to work around the problem.
