### ISSUE TITLE
Profiling using nvprof

### ISSUE THREAD

**Issue by rroohhh** [N-BodyShop/changa#57]
Hi,
I am trying to profile `ChaNGa` using `nvprof`, but unfortunately it crashes when doing so.
I am running using `nvprof $(which ChaNGa) lambs.param` and get the following output:
```
Charm++> No provisioning arguments specified. Running with a single PE.
         Use +auto-provision to fully subscribe resources or +p1 to silence this message.
Charm++: standalone mode (not using charmrun)
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.1
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc
_sync'.
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (2 sockets x 16 cores x 2 PUs = 64-way SMP)
Charm++> cpu topology info is gathered in 0.004 seconds.
==154679== NVPROF is profiling process 154679, command: /home/scc/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.2.0/changa-master-jzyqizec6y2bzqas6fyanfqqh4j2pmkl/bin/ChaNGa lambs.param
[0] MultistepLB_notopo created
WARNING: bStandard parameter ignored; Output is always standard.
Not Using CkLoop 0
INFO: localNodes: 1.000000
INFO: remoteNodes: 1.000000
INFO: remoteResumeNodes: 1.000000
INFO: localParts: 0.100000
INFO: remoteParts: 0.100000
INFO: remoteResumeParts: 0.100000
INFO: largePhaseThreshold: 0.000000
ChaNGa version 3.4, commit 5414a92
Running on 1 processors/ 1 nodes with 8 TreePieces
==154679== Profiling application: /home/scc/spack/opt/spack/linux-centos7-skylake_avx512/gcc-8.2.0/changa-master-jzyqizec6y2bzqas6fyanfqqh4j2pmkl/bin/ChaNGa lambs.param
==154679== Profiling result:
No kernels were profiled.
No API activities were profiled.
==154679== Warning: Some profiling data are not recorded. Make sure cudaProfilerStop() or cuProfilerStop() is called before application exit to flush profile data.
======== Error: Application received signal 11
```

This is running ChaNGa commit `3129c3c2285cf65d3dc3e1302e61b92c81878593` and charm `6.10.1`

**Comment by trquinn** [comment]
I had this problem on the Comet GPU systems back in December.  Here is that conversation:

 [Ticket created from XUP by trq]
[From: Thomas Quinn]
[System: Comet GPU]
[Category: System/Hardware Issues]
I'm getting the following error when trying to "nvprof" my application.

==50234== Error: Internal profiling error 4087:35.
======== Profiling result:
No kernels were profiled.
No API activities were profiled.
======== Error: CUDA profiling error.

A web search indicates that  this has to do with "non-admin user access.".
 
 ----------------------------------------------------------------
   Complete Ticket History
 ----------------------------------------------------------------
 
 Subject: XUP: nvprof failing
From: Mahidhar Tatineni
Time: Fri Dec 13 16:02:48 2019

Thanks for letting us know. I think we need to do change the profiling
setting with a modprobe command. I will let you know once its done.

Mahidhar



On 2019-12-13 15:27:12, portal wrote:
> [Ticket created from XUP by trq]
> [From: Thomas Quinn]
> [System: Comet GPU]
> [Category: System/Hardware Issues]
> I'm getting the following error when trying to "nvprof" my
application.
>
> ==50234== Error: Internal profiling error 4087:35.
> ======== Profiling result:
> No kernels were profiled.
> No API activities were profiled.
> ======== Error: CUDA profiling error.
>
> A web search indicates that  this has to do with "non-admin user
access.".


------------------------------------------------
Subject: XUP: nvprof failing
From: Mahidhar Tatineni
Time: Thu Mar 12 00:52:06 2020

Thomas

I just wanted to follow up on this old ticket. The change is in place
to enable profiling and I verifed that this works [1].

Mahidhar

[mahidhar@comet-33-02 release]$ module load cuda

**Comment by trquinn** [comment]
@rroohhh : any progress with this?

**Comment by trquinn** [comment]
No update.  I'll assume my suggestion worked.  Closing.
