### ISSUE TITLE
Interface to grackle cooling is not correct for comoving coordinates.

### ISSUE THREAD

**Issue by trquinn** [N-BodyShop/changa#76]
![PDF_z8_changa_sm](https://user-images.githubusercontent.com/5175698/88755461-15982680-d116-11ea-8dab-a9170d55896c.png)
The attached image from an AGORA simulation at z = 8 shows a bump in the minimum temperature at rho ~ 1e-24 gm/cc.  Comparing to other codes, this bump should be at rho ~ 1e-27.  This is likely a bad conversion to comoving densities.

**Comment by N-body-group-Reed** [comment]
Excellent. I hope the fix is working.

**Comment by trquinn** [comment]
![rho_T_z8](https://user-images.githubusercontent.com/5175698/90284161-62724180-de26-11ea-88f2-c36afe2b7bb9.png)
Here is what it looks like now.  This compares well with the GEAR, RAMSES, and GIZMO plots from the AGORA paper.

**Comment by N-body-group-Reed** [comment]
Fantastic temp-density plot: the bump is perfectly shifted now. Such great
news.

My GitHub understanding is weak: I tried cloning your pull request to
Comet. No dice.
Is the corrected version of ChaNGa obtained in the standard git clone way?

johnny
