### ISSUE TITLE
Release testing with Charm++ v7.0.0

### ISSUE THREAD

**Issue by minitu** [N-BodyShop/changa#84]
- Jaemin: OLCF Summit, PSC Bridges, SDSC Comet
- Justin: TACC Stampede2
- Tom: TACC Frontera

**Comment by minitu** [comment]
@trquinn I can confirm that `teststep` works for all combinations of SMP, non-SMP, CUDA and non-CUDA on Summit, Bridges, and Comet.

**Comment by trquinn** [comment]
Note the title update to correct charm version number.

**Comment by trquinn** [comment]
Release 3.5 is out.
